DROP TABLE IF EXISTS media CASCADE;
--In PostgreSQL, DROP CONSTRAINT must be used within an ALTER TABLE statement, specifying which table the constraint belongs to. Try modifying it like this:
--DROP CONSTRAINT IF EXISTS FK3aix2chsvr6pv5oaonxxphjox;
drop table if exists messages cascade;
drop table if exists online_status cascade;
drop table if exists users cascade;
drop sequence if exists messages_seq;

create sequence messages_seq start with 1 increment by 50;

create table media (
    id bigint generated by default as identity,
    size bigint,
    name varchar(255),
    type varchar(255),
    url varchar(255),
    primary key (id)
);

create table messages (
    id bigint not null,
    media_id bigint unique,
    timestamp timestamp(6),
    content varchar(255),
    content_type varchar(255) check (content_type in ('TEXT','IMAGE','VIDEO','AUDIO','FILE')),
    receiver_id varchar(255),
    sender_id varchar(255),
    status varchar(255) check (status in ('PENDING','DELIVERED','READ','DELETED')),
    primary key (id)
);

create table online_status (
    last_seen timestamp(6),
    status varchar(255) check (status in ('ONLINE','OFFLINE')),
    user_id varchar(255) not null,
    primary key (user_id)
);

create table users (
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    auth_provider varchar(255) check (auth_provider in ('LOCAL','GOOGLE','FACEBOOK','GITHUB','APPLE')),
    email varchar(255) unique,
    full_name varchar(255),
    password varchar(255),
    phone_number varchar(255) unique,
    primary_login_method varchar(255) check (primary_login_method in ('EMAIL','PHONE','USERNAME','OAUTH')),
    profile_url varchar(255),
    provider_id varchar(255),
    user_id varchar(255) not null,
    username varchar(255) unique,
    primary key (user_id)
);

ALTER TABLE messages DROP CONSTRAINT IF EXISTS FK3aix2chsvr6pv5oaonxxphjox;

alter table if exists messages
   add constraint FK3aix2chsvr6pv5oaonxxphjox
   foreign key (media_id)
   references media;